plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'db/queue_schema.rb'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/migrations/trackables.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# * Application Cops
Layout/LineLength:
  Enabled: true
  Max: 118
  AllowedPatterns: ['^(\s*#)', '.*\s+#']

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_first_parameter

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/Documentation:
  Enabled: false

# * RSpec Cops
RSpec/IncludeExamples:
  Enabled: true

RSpec/ExampleLength:
  Max: 18
