# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec

# Application Cops
Layout/LineLength:
  Enabled: true
  Max: 118
  AllowedPatterns: ['^(\s*#)', '.*\s+#']

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_first_parameter

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# RSpec Cops
RSpec/IncludeExamples:
  Enabled: true
