services:
  db:
    image: postgres:17-alpine
    container_name: togglin_db
    restart: always
    ports:
      - 5101:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: togglin_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - togglin_network
    volumes:
      - togglin_db:/var/lib/postgresql/data

volumes:
  togglin_db:

networks:
  togglin_network:
    driver: bridge
    name: togglin_network
